Repository brun0vieira/personal-finance-tracker, pull requests merged in 2022-10, with the labels that each got.

#2 Changes
  helpers.py
  main.py
  personal_finance_tracker.py
Labels: hacktoberfest

#3 Commands file
  commands.py
  constants.py
  personal_finance_tracker.py
Labels: hacktoberfest

#6 added selected currency when adding expense
  personal_finance_tracker.py
Labels: hacktoberfest, hacktoberfest-accepted

#7 Add expense
  config/__init__.py
  config/configurations.py
  config/constants.py
  config/paths.py
  core/__init__.py
  core/commands.py
  helpers.py
  main.py
  personal_finance_tracker.py
  pftUserData/my_config.json
  pftUserData/my_data.json
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
